### ISSUE TITLE
vpnclient needs to run in `host_mode`

### ISSUE THREAD

**Issue by cjdcordeiro** [mF2C/vpn#1]
please update the compose file

**Comment by jjensenral** [comment]
If I set network mode to host in the d-c file in this repository, then the client fails because the client cannot resolve the `vpnserver` domain name. However, setting network to host in a standalone client - connecting to the cloud VPN server - works, because in this environment the client has the IP address of the server.

**Comment by jjensenral** [comment]
This is now done. Host mode is set in the agent d-c file.
